### ISSUE TITLE
Use .DirIcon as the logo

### ISSUE THREAD

**Issue by probonopd** [Alexsussa/AIDM#1]
You can use the `.DirIcon` stored inside the AppImage as the logo...

**Comment by Alexsussa** [comment]
Thank you by suggestion. AppImage was created and added to download.

**Comment by probonopd** [comment]
Maybe I was not clear, but what I meant to say is:

This is unnecessary

![image](https://user-images.githubusercontent.com/2480569/90251886-0ca19780-de2e-11ea-89de-b3ca98935643.png)

because every AppImage contains a `.DirIcon` which you can use without having to ask the user for  an icon.
