### ISSUE TITLE
AIDM.AppImage

### ISSUE THREAD

**Issue by probonopd** [Alexsussa/AIDM#3]
Please provide AIDM itself as an AppImage.
https://github.com/AppImage/awesome-appimage/blob/main/README.md#deployment-tools-for-python-applications can help.

**Comment by Alexsussa** [comment]
Thanks by informations. I'm working on AIDM to AppImage development too.

**Comment by Alexsussa** [comment]
Thank you by suggestion. AppImage was created and added to download.

**Comment by probonopd** [comment]
Hello, thanks for making the AppImage. Unforunately it doesn't run on Ubuntu 20.04:

```
Error loading Python lib '/tmp/_MEIn9Lfqx/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIn9Lfqx/libpython3.11.so.1.0)
```

AppImage was built on a too new system and cannot run on all Ubuntu LTS versions. Could you please build one that runs on all still-supported releases of Ubuntu? Thanks.

**Comment by Alexsussa** [comment]
Hello, @probonopd, try to install python3.11 and try to run AIDM again.

**Comment by probonopd** [comment]
Hi @Alexsussa, the point of AppImage is that it should be bundled so that the user doesn't need to do anything. Thanks!

Maybe you'd like to check out
https://github.com/niess/python-appimage
